### ISSUE TITLE
Práctica 5: Métricas de calidad con SonarCloud.

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-con-sonarcloud-entrevista-metztli_team#1]
[Métricas de calidad con SonarCloud.pdf](https://github.com/SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-con-sonarcloud-entrevista-metztli_team/files/9678263/Metricas.de.calidad.con.SonarCloud.pdf)

**Comment by javiern-778** [comment]
20/20

**Comment by josealfredo79** [comment]
Falto agregar las actividades de moprosoft

**Comment by josealfredo79** [comment]
Calificación 17

**Comment by josealfredo79** [comment]
Revisado..

**Comment by josealfredo79** [comment]
@Ferch0419 favor de revisar bien...
